const ASSETS = 'https://threejs.org/examples/';

export const PRESETS = {
  furniture: {
    id: 'furniture',
    label: 'Furniture',
    headline: '3D product viewer',
    tagline: 'Lounge chair — fabric & frame finishes',
    model: {
      type: 'gltf',
      url: `${ASSETS}models/gltf/SheenChair.glb`,
    },
    camera: {
      position: [-0.9, 0.75, 1.4],
      target: [0, 0.35, 0],
      minDistance: 0.8,
      maxDistance: 6,
    },
    environment: 'room',
    background: 0xbbbbbb,
    variantLabels: {
      'Mango Velvet': 'Warm linen',
      'Peacock Velvet': 'Deep teal',
    },
    defaultVariant: 'Mango Velvet',
    guiType: 'variants',
  },

  macbook: {
    id: 'macbook',
    label: 'MacBook',
    headline: '3D product viewer',
    tagline: 'MacBook Pro — finish options',
    model: {
      type: 'gltf',
      url: '/models/macbook-pro.glb',
    },
    modelTargetHeight: 0.34,
    camera: {
      position: [0.6, 0.28, 0.75],
      target: [0, 0.12, 0],
      minDistance: 0.35,
      maxDistance: 2.5,
    },
    environment: 'room',
    background: 0x000000,
    finishes: [
      {
        id: 'silver',
        label: 'Silver',
        body: 0xd8dce3,
        keyboard: 0x3a3f48,
        screen: 0x0a0a0c,
        screenEmissive: 0x1a2a44,
        metalness: 0.9,
        roughness: 0.35,
        applyToUnmatched: true,
      },
      {
        id: 'space-gray',
        label: 'Space Gray',
        body: 0x6e7378,
        keyboard: 0x2a2d30,
        screen: 0x08080a,
        screenEmissive: 0x152238,
        metalness: 0.88,
        roughness: 0.4,
        applyToUnmatched: true,
      },
      {
        id: 'midnight',
        label: 'Midnight',
        body: 0x2c3138,
        keyboard: 0x1a1c1f,
        screen: 0x050508,
        screenEmissive: 0x0f1a33,
        metalness: 0.85,
        roughness: 0.45,
        applyToUnmatched: true,
      },
      {
        id: 'starlight',
        label: 'Starlight',
        body: 0xe8dfd0,
        keyboard: 0x4a4540,
        screen: 0x0a0a0c,
        screenEmissive: 0x223355,
        metalness: 0.88,
        roughness: 0.38,
        applyToUnmatched: true,
      },
    ],
    defaultFinish: 'silver',
    guiType: 'color',
  },

  saas: {
    id: 'saas',
    label: 'SaaS',
    headline: '3D product viewer',
    tagline: 'Abstract device — brand color themes',
    model: { type: 'procedural' },
    camera: {
      position: [1.8, 1.1, 2.2],
      target: [0, 0.35, 0],
      minDistance: 1.2,
      maxDistance: 8,
    },
    environment: 'room',
    background: 0x0f1218,
    finishes: [
      {
        id: 'cloud',
        label: 'Cloud white',
        body: 0xf0f2f5,
        accent: 0x4a9eff,
        screen: 0x1a2332,
        screenEmissive: 0x3366cc,
      },
      {
        id: 'graphite',
        label: 'Graphite',
        body: 0x3a3f48,
        accent: 0x7c5cff,
        screen: 0x0d1117,
        screenEmissive: 0x5533aa,
      },
      {
        id: 'coral',
        label: 'Coral accent',
        body: 0x2a2d33,
        accent: 0xff6b4a,
        screen: 0x141820,
        screenEmissive: 0xcc4422,
      },
    ],
    defaultFinish: 'cloud',
    guiType: 'procedural',
  },
};

export const PRESET_IDS = Object.keys(PRESETS);
